services:
    lapisOpen:
        image: ghcr.io/genspectrum/lapis:${LAPIS_TAG}
        ports:
            - ${LAPIS_PORT}:8080
        command: --silo.url=http://silo:8081
        volumes:
            - type: bind
              source: ${TESTSET_DATA_FOLDER}/database_config.yaml
              target: /workspace/database_config.yaml
              read_only: true
            - type: bind
              source: ${TESTSET_DATA_FOLDER}/reference_genomes.json
              target: /workspace/reference_genomes.json
              read_only: true
        healthcheck: # TODO(https://github.com/GenSpectrum/LAPIS-SILO-e2e/issues/32) Remove at some point
            test:
                [
                    'CMD-SHELL',
                    'wget -qO- http://localhost:8080/sample/aggregated | grep -o ''"count":[0-9]*'' | sed ''s/[^0-9]//g'' | xargs test 0 -ne || exit 1',
                ]
            interval: 2s
            timeout: 5s
            retries: 10
        stop_grace_period: 0s

    silo:
        image: ghcr.io/genspectrum/lapis-silo:${SILO_TAG}
        ports:
            - ${SILO_PORT}:8081
        command: --api
        volumes:
            - type: bind
              source: ${TESTSET_OUTPUT_FOLDER}/
              target: /data
              read_only: true
        depends_on:
            siloPreprocessing:
                condition: service_completed_successfully
        stop_grace_period: 0s

    siloPreprocessing:
        image: ghcr.io/genspectrum/lapis-silo:${SILO_TAG}
        command: --preprocessing
        volumes:
            - type: bind
              source: ${TESTSET_OUTPUT_FOLDER}/
              target: /preprocessing/output
              read_only: false
            - type: bind
              source: ${TESTSET_DATA_FOLDER}/
              target: /preprocessing/input
              read_only: false
            - type: bind
              source: ${TESTSET_DATA_FOLDER}/preprocessing_config.yaml
              target: /app/preprocessing_config.yaml
              read_only: true
            - type: bind
              source: ${TESTSET_DATA_FOLDER}/database_config.yaml
              target: /app/database_config.yaml
              read_only: true
        stop_grace_period: 0s
