import { TestCase } from '../../../testCase.ts';
const test: TestCase = {
    name: 'Query that requests many metadata columns and sorts it by three fields',
    endpoint: '/sample/details',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: {
        fields: [
            'accession',
            'bodyProduct',
            'breadthOfCoverage',
            'cellLine',
            'frameShifts_L',
            'frameShifts_M',
            'frameShifts_S',
            'geoLocAdmin1',
            'geoLocAdmin2',
            'geoLocCity',
            'geoLocCountry',
            'geoLocSite',
            'groupId',
            'groupName',
            'hostAge',
            'hostAgeBin',
            'hostDisease',
            'hostGender',
            'hostHealthOutcome',
            'hostHealthState',
            'hostNameCommon',
            'hostNameScientific',
            'hostOriginCountry',
            'hostRole',
            'hostTaxonId',
            'hostVaccinationStatus',
            'insdcAccessionBase_L',
            'insdcAccessionBase_M',
            'insdcAccessionBase_S',
            'insdcAccessionFull_L',
            'insdcAccessionFull_M',
            'insdcAccessionFull_S',
            'insdcVersion_L',
            'insdcVersion_M',
            'insdcVersion_S',
            'isLabHost',
            'isRevocation',
            'length_L',
            'length_M',
            'length_S',
            'ncbiReleaseDate',
            'ncbiSourceDb',
            'ncbiSubmitterCountry',
            'ncbiUpdateDate_L',
            'ncbiUpdateDate_M',
            'ncbiUpdateDate_S',
            'ncbiVirusName',
            'ncbiVirusTaxId',
            'passageMethod',
            'passageNumber',
            'presamplingActivity',
            'previousInfectionDisease',
            'previousInfectionOrganism',
            'sequencingDate',
            'sequencingInstrument',
            'sequencingProtocol',
            'signsAndSymptoms',
            'specimenCollectorSampleId',
            'specimenProcessing',
            'specimenProcessingDetails',
            'sraRunAccession',
            'stopCodons',
            'submissionId',
            'submittedAtTimestamp',
            'submittedDate',
            'submitter',
            'travelHistory',
            'version',
            'versionComment',
            'versionStatus',
        ],
        orderBy: [
            {
                field: 'geoLocCountry',
                type: 'descending',
            },
            {
                field: 'accession',
                type: 'ascending',
            },
            {
                field: 'version',
                type: 'ascending',
            },
        ],
    },
    expectedStatusCode: 200,
    expectedResponse: {
        relativeFilePath: 'test1_result.json.zst',
        decompressFile: true,
    },
};
export default test;
